### ISSUE TITLE
habrAjax

### ISSUE THREAD

**Issue by PalePyth** [spmbt/haPages#10]
Здесь http://habrahabr.ru/post/146200/ указывается, что есть скрипт для просмотра кэша ВК, который скачивается тут https://greasyfork.org/en/scripts/1970-habrajax
Вопрос: а как же собственно это работает, как посмотреть кэш?
Собственно, вот здесь https://vk.com/wall-105079216_10963 потёрты комменты, хотелось бы как-нибудь восстановить.

**Comment by spmbt** [comment]
Нет, всё это обсуждали лишь применительно к восстановлению закрытых / удалённых статей с Хабра. Не вообще про кеш ВК. Про то, есть ли где-либо кеш для ВК - не в курсе.
