### ISSUE TITLE
HabraDarkAge и левое меню

### ISSUE THREAD

**Issue by BorzdeG** [spmbt/haPages#2]
При размере страницы от 1557px*732px (до пикселя не проверял), меню слева превращается в "тыкву". Появилось в версии 423.2014.11.22.
Firefox 33.1.1

![Image](http://habrastorage.org/files/7c1/b93/014/7c1b930142794a0bbbc4d0b7bc9c34a9.png)

**Comment by spmbt** [comment]
В чём состоит проблема? Именно так в этой версии было задумано и это висело в планах с 4 ноября:
- адаптивно к широким экранам - постоянно видимое меню, как в ZenComment;

**Comment by BorzdeG** [comment]
1) выглядит ужастно! размер шрифта слишком большой
2) счётчики наезжают/перекрываются тенями
3) фон наезжает на пейджинг справа
4) кнопку "Новая публикация" вообще не сразу заметил среди текста

**Comment by spmbt** [comment]
Благодарю, кое-что подправил.
1) размер шрифта был взят тем же, что у стандартного меню. Предложите ваш вариант. Почему его нужно менять?
2) счётчики исправил по #navbar .nav_tabs_content .nav_tab .menu a .count:not(:empty){z-index: 1; opacity: 0.7;}
3) этим экономятся 10 пикс ширины, ради которых пришлось бы показывать меню не с 1520, а с 1530. Но ширина наезда выбрана не случайно, это - отступ до букв меню;
4) Решения могут быть разные. Например в ZenComment "Новая публикация висит вверху в первом ряду. Вынесена направо вследствие малой востребованности её в потоке статьи или ленты.

**Comment by BorzdeG** [comment]
1) просто поменьше бы сделать... например раза в 1,5
3) если уменьшить на пару пикселей, то не будет перекрытия

**Comment by spmbt** [comment]
1) это не помешает, уменьшит мин. высоту где-то до 550-500, но требует большой переработки блока кода и тестирования на сбалансированность цветов, на шаги @media (min-width...). Если есть желание - сделайте, я посмотрю результат, подпилю и выложу. (Мне лично широкий экран не актуален, предпочтений нет.) Можно сделать ещё более интересный сценарий адаптивности с частичным занятием левого поля или уменьшением его (затем возникает закономерный вопрос: а нужны ли огромные кнопки вообще?).

3) наверное, лучше отодвинуть на 2 или больше пикселей - всё равно места очень много. Сделал
    .page-nav .next-prev{left:-91px}
    .page-nav #nav-pages{left:-95px}

**Comment by iamkarlson** [comment]
Действительно ужасно выглядит. Правда больше напрягает что счетчики на текст наехавшие.
