### ISSUE TITLE
Пропадает текст

### ISSUE THREAD

**Issue by BorzdeG** [spmbt/haPages#3]
В [статье](http://habrahabr.ru/post/244255/) пропадает весь текст из HTML кода. На других страницах ошибки нет. Так же текст появляется при отключении HabraDarkAge в Stylish

**Comment by spmbt** [comment]
Не воспроизводится (Fx, Chrome - Win7-64), эта статья отображается без каких-либо особенностей по сравнению с другими (с авторизацией и без). Могло ли быть такое, что включен другой юзерстиль? У этого, как и у его прототипа, есть эффект пропадания текста при смешивании с ZenComment, например. Но для всех страниц.

**Comment by BorzdeG** [comment]
автор поправил статью - сейчас отображается корректно. Возможно ошибка в вёрстке была...

**Comment by spmbt** [comment]
Надо было отключить все стили и скрипты, и затем Ctrl-S. В будущем хотелось бы увидеть случай, когда ломается.

**Comment by BorzdeG** [comment]
учту)
