### ISSUE TITLE
Счетчики наезжают на меню

### ISSUE THREAD

**Issue by iamkarlson** [spmbt/haPages#4]
![image](https://cloud.githubusercontent.com/assets/4534374/10569725/88533f88-763b-11e5-87c9-5bea38b2a377.png)

**Comment by spmbt** [comment]
Эта часть оформлена с целью компактности блока, но требует доработки в плане отображения данных. В целом, спасибо за ряд обозначенных проблем.

**Comment by spmbt** [comment]
Исправлено
