### ISSUE TITLE
Информация о компании, в чьем блоге размещен пост, наезжает на меню похожие публикации

### ISSUE THREAD

**Issue by iamkarlson** [spmbt/haPages#5]
![image](https://cloud.githubusercontent.com/assets/4534374/10569734/aa797910-763b-11e5-8f12-c428dd7fe78f.png)

**Comment by spmbt** [comment]
Не наезжает, а прикреплена к правой стороне колонки. Проверить можно, написав в браузере длинные имена для похожих публикаций - они не будут наезжать на информацию о компании.
