### ISSUE TITLE
Лучшее на других сайтах не окрашено в общий цвет

### ISSUE THREAD

**Issue by iamkarlson** [spmbt/haPages#6]
![image](https://cloud.githubusercontent.com/assets/4534374/10569748/d35f1a2e-763b-11e5-8682-576478523ee0.png)

**Comment by spmbt** [comment]
Приветствую пулл-реквесты для исправления этих стилей. Также, не против их ужать в размерах, т.к. занимают треть страницы.

**Comment by spmbt** [comment]
Сделано.
