### ISSUE TITLE
Подсветка кнопок на панели не перекрывает полностью кнопку.

### ISSUE THREAD

**Issue by iamkarlson** [spmbt/haPages#7]
![screenshot_0262](https://cloud.githubusercontent.com/assets/4534374/10569761/ff7ef8b8-763b-11e5-96e8-b8c8d37f3a6f.png)

**Comment by spmbt** [comment]
Это так задумано, чтобы с левой сторны имелась возможность видеть пагинацию в окнах малой высоты для лент разного типа и нажимать на кнопки выбора страниц.
