### ISSUE TITLE
Кнопки навигации на другие сайты не вписываются в сетку

### ISSUE THREAD

**Issue by iamkarlson** [spmbt/haPages#8]
![image](https://cloud.githubusercontent.com/assets/4534374/10569775/1fdbb0b0-763c-11e5-8044-a330cd9a176b.png)

**Comment by spmbt** [comment]
Они висят как отдельное меню, видимое при наведении. Но сейчас, в связи со сменой стилей сайта, они видны постоянно. Приветствуются пулл-реквесты.

**Comment by spmbt** [comment]
Меню восстановлено в прежнем виде , как на указанном скриншоте.
